### ISSUE TITLE
You must be the owner of the application

### ISSUE THREAD

**Issue by DogAndHerDude** [Weebly/weeblybundler#3]
Well... I am

I'm running the command from npm scripts

`WEEBLY_SECRET=my_secret WEEBLY_CLIENT_ID=my_id weeblybundle app .tmp/client/public`

Do I need any specific permissions or something?

**Comment by bdeanindy** [comment]
It appears that there is a `WEEBLY_DOMAIN` that must be set in order for this to operate, but when set, the operation is FORBIDDEN (403).

```
$ weeblybundle app ./
/Users/benjamin/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response': 403 Forbidden (RestClient::Forbidden)
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
	from /Users/benjamin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:877:in `start'
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient.rb:71:in `post'
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/gems/weeblybundler-0.1.1/lib/weeblybundler/bundle.rb:77:in `uploadApp'
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/gems/weeblybundler-0.1.1/lib/weeblybundler/bundle.rb:52:in `sync'
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/gems/weeblybundler-0.1.1/lib/weeblybundler/cli.rb:26:in `handleApp'
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/gems/weeblybundler-0.1.1/lib/weeblybundler/cli.rb:71:in `app'
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/gems/weeblybundler-0.1.1/bin/weeblybundle:5:in `<top (required)>'
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/bin/weeblybundle:23:in `load'
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/bin/weeblybundle:23:in `<main>'
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/benjamin/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```
